name: Build and Deploy to gke

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: gtihubaction-kubernetes
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: github-actions-gke-deployement
  IMAGE: github-actions-gke-image
  TAG: 1.0.0

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
    